// This file is automatically generated by qtc from "board.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template/board.qtpl:1
package template

//line template/board.qtpl:1
import (
	"github.com/tiehuis/gorum/model"
)

//line template/board.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/board.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/board.qtpl:6
type BoardPage struct {
	Board   model.Board
	Threads []model.Post
}

//line template/board.qtpl:12
func (bp *BoardPage) StreamBody(qw422016 *qt422016.Writer) {
	//line template/board.qtpl:12
	qw422016.N().S(`
<pre>
    <span><a href="/">Home</a></span>
    <h3><a href="/board/`)
	//line template/board.qtpl:15
	qw422016.E().S(bp.Board.Code)
	//line template/board.qtpl:15
	qw422016.N().S(`">/`)
	//line template/board.qtpl:15
	qw422016.E().S(bp.Board.Code)
	//line template/board.qtpl:15
	qw422016.N().S(`/ - `)
	//line template/board.qtpl:15
	qw422016.E().S(bp.Board.Name)
	//line template/board.qtpl:15
	qw422016.N().S(`</a></h3>

    <div><label for="show-new-post">+[New Thread]</label></div>
    <input id="show-new-post" type=checkbox>
    <div id="new-post" class="hidden">
        <form action="/board/`)
	//line template/board.qtpl:20
	qw422016.E().S(bp.Board.Code)
	//line template/board.qtpl:20
	qw422016.N().S(`" method="post">
            <textarea required name="content" spellcheck="true" rows="2" maxlength="2000" placeholder="New Thread"></textarea>
            <input type="submit" value="send">
        </form>
    </div>

    <table>
    <tr>
        <th>post</th>
        <th>content</th>
    </tr>
    `)
	//line template/board.qtpl:31
	for _, p := range bp.Threads {
		//line template/board.qtpl:31
		qw422016.N().S(`
        <tr>
            <td><a href="/board/`)
		//line template/board.qtpl:33
		qw422016.E().S(bp.Board.Code)
		//line template/board.qtpl:33
		qw422016.N().S(`/`)
		//line template/board.qtpl:33
		qw422016.E().V(p.Id)
		//line template/board.qtpl:33
		qw422016.N().S(`">`)
		//line template/board.qtpl:33
		qw422016.E().V(p.Id)
		//line template/board.qtpl:33
		qw422016.N().S(`</a></td>
            <td>`)
		//line template/board.qtpl:34
		qw422016.E().S(p.Content)
		//line template/board.qtpl:34
		qw422016.N().S(`</td>
        </tr>
    `)
		//line template/board.qtpl:36
	}
	//line template/board.qtpl:36
	qw422016.N().S(`
    </table>
</pre>
`)
//line template/board.qtpl:39
}

//line template/board.qtpl:39
func (bp *BoardPage) WriteBody(qq422016 qtio422016.Writer) {
	//line template/board.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/board.qtpl:39
	bp.StreamBody(qw422016)
	//line template/board.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line template/board.qtpl:39
}

//line template/board.qtpl:39
func (bp *BoardPage) Body() string {
	//line template/board.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/board.qtpl:39
	bp.WriteBody(qb422016)
	//line template/board.qtpl:39
	qs422016 := string(qb422016.B)
	//line template/board.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/board.qtpl:39
	return qs422016
//line template/board.qtpl:39
}
