// This file is automatically generated by qtc from "layout_base.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template/layout_base.qtpl:1
package template

//line template/layout_base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/layout_base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/layout_base.qtpl:2
type Page interface {
	//line template/layout_base.qtpl:2
	Body() string
	//line template/layout_base.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
	//line template/layout_base.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line template/layout_base.qtpl:2
}

//line template/layout_base.qtpl:7
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
	//line template/layout_base.qtpl:7
	qw422016.N().S(`
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>gorum</title>
        <link rel="stylesheet" href="/static/gorum.css" />
    </head>
    <body>
        `)
	//line template/layout_base.qtpl:16
	p.StreamBody(qw422016)
	//line template/layout_base.qtpl:16
	qw422016.N().S(`
    </body>
</html>
`)
//line template/layout_base.qtpl:19
}

//line template/layout_base.qtpl:19
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
	//line template/layout_base.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template/layout_base.qtpl:19
	StreamPageTemplate(qw422016, p)
	//line template/layout_base.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line template/layout_base.qtpl:19
}

//line template/layout_base.qtpl:19
func PageTemplate(p Page) string {
	//line template/layout_base.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
	//line template/layout_base.qtpl:19
	WritePageTemplate(qb422016, p)
	//line template/layout_base.qtpl:19
	qs422016 := string(qb422016.B)
	//line template/layout_base.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
	//line template/layout_base.qtpl:19
	return qs422016
//line template/layout_base.qtpl:19
}
