// This file is automatically generated by qtc from "gorum.css.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line static/gorum.css.qtpl:1
package static

//line static/gorum.css.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line static/gorum.css.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line static/gorum.css.qtpl:1
func StreamStyleSheet(qw422016 *qt422016.Writer) {
	//line static/gorum.css.qtpl:1
	qw422016.N().S(`
body {
    margin: 25px 100px 25px 100px
}

.hidden {
    display: none
}

/* toggles an arbitrary div using an arbitrary label, see board.qtpl for usage */
input[type=checkbox] {
    display: none;
}
input[type=checkbox]:checked + div {
    display: block !important;
}

`)
//line static/gorum.css.qtpl:18
}

//line static/gorum.css.qtpl:18
func WriteStyleSheet(qq422016 qtio422016.Writer) {
	//line static/gorum.css.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line static/gorum.css.qtpl:18
	StreamStyleSheet(qw422016)
	//line static/gorum.css.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line static/gorum.css.qtpl:18
}

//line static/gorum.css.qtpl:18
func StyleSheet() string {
	//line static/gorum.css.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
	//line static/gorum.css.qtpl:18
	WriteStyleSheet(qb422016)
	//line static/gorum.css.qtpl:18
	qs422016 := string(qb422016.B)
	//line static/gorum.css.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
	//line static/gorum.css.qtpl:18
	return qs422016
//line static/gorum.css.qtpl:18
}
